# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadConteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CantidadConteo',
                'verbose_name_plural': 'CantidadesConteos',
            },
        ),
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_fisico', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estatus', models.CharField(choices=[('abierto', 'Abierto'), ('proceso', 'En proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='abierto', max_length=50)),
                ('prioridad', models.CharField(choices=[('programa', 'Programa'), ('especial', 'Especial'), ('critico', 'Critico')], default='programa', max_length=50)),
                ('cantidad_sap', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo',
                'verbose_name_plural': 'Conteos',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_pieza', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=100)),
                ('unidad', models.CharField(choices=[('kg', 'KG'), ('pieza', 'Pieza'), ('contenedor', 'Contenedor'), ('caja', 'Caja'), ('tonel', 'Tonel')], max_length=50)),
                ('piezas_unidad', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='conteo',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_ciclico.Pieza'),
        ),
        migrations.AddField(
            model_name='cantidadconteo',
            name='conteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_ciclico.Conteo'),
        ),
        migrations.AddField(
            model_name='cantidadconteo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_ciclico.Ubicacion'),
        ),
    ]
